services:
  weaviate:
    image: semitechnologies/weaviate:1.18.0
    platform: linux/amd64  # Force AMD64 emulation
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      IMG2VEC_NEURAL_HOST: 'http://t2v-neural:8080'
      IMG2VEC_NEURAL_IMAGE_HEIGHT: '224'
      IMG2VEC_NEURAL_IMAGE_WIDTH: '224'
    depends_on:
      - t2v-neural
    restart: unless-stopped

  t2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    platform: linux/amd64  # Force AMD64 emulation
    environment:
      ENABLE_CUDA: '0'
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  weaviate_data:
