services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.23.5
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      IMAGE_INFERENCE_API: 'http://t2v-neural:8080'  # Critical addition
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      t2v-neural:
        condition: service_healthy
    restart: unless-stopped

  t2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/.well-known/ready"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  weaviate_data:
